# vsim -modelsimini C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/modelsim/modelsim.ini -wlf C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/test_output/testbench_lib.svpwm_vunit_tb.svpwm_check_reset1d0b762898fba60754b72483b94fa1ee0b9df65e/modelsim/vsim.wlf -quiet -t ps -onfinish stop testbench_lib.svpwm_vunit_tb(tb) "+notimingchecks" -L vunit_lib -L design_lib -L testbench_lib -g/svpwm_vunit_tb/runner_cfg="active python runner : true,enabled_test_cases : svpwm_check_reset_values,output path : C::/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/test_output/testbench_lib.svpwm_vunit_tb.svpwm_check_reset1d0b762898fba60754b72483b94fa1ee0b9df65e/,tb path : C::/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/test_benches/,use_color : true" 
# Start time: 02:24:08 on Feb 12,2022
# ** Warning: (vsim-1425) C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/svpwm_vunit_tb.vhd(117): Absolute pathname for a VHDL external name does not start
# with an entity name that is a design root. Instead, an object with the name 'svpwm_tb_inst'
# was found in the scope of design root 'svpwm_vunit_tb'. This object was used as the starting
# point of the external name.
#    Time: 0 ps  Iteration: 0  Instance: /svpwm_vunit_tb File: C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/svpwm_vunit_tb.vhd
# ** Warning: (vsim-1425) C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/svpwm_vunit_tb.vhd(117): Absolute pathname for a VHDL external name does not start
# with an entity name that is a design root. Instead, an object with the name 'svpwm_tb_inst'
# was found in the scope of design root 'svpwm_vunit_tb'. This object was used as the starting
# point of the external name.
#    Time: 0 ps  Iteration: 0  Instance: /svpwm_vunit_tb File: C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/svpwm_vunit_tb.vhd
# ** Warning: (vsim-8523) Cannot reference the signal "/svpwm_vunit_tb/svpwm_tb_inst/counter" before it has been elaborated.
#    Time: 0 ps  Iteration: 0  Instance: /svpwm_vunit_tb File: C:/Users/mgann/Xilinix_Projects/svpwm_PL/vunit_tests/vunit_out/preprocessed/testbench_lib/svpwm_vunit_tb.vhd
# ** Warning: Design size of 21942 statements exceeds ModelSim-Intel FPGA Starter Edition recommended capacity.
# Expect performance to be adversely affected.
#             [22;96;49m0 ps[0m - [1;37;49mdefault[0m              -    [1;37;49mINFO[0m - -------------------------------------------------------------------------------- (svpwm_vunit_tb.vhd:179)
#             [22;96;49m0 ps[0m - [1;37;49mdefault[0m              -    [1;37;49mINFO[0m - TEST CASE: svpwm_check_reset_values (svpwm_vunit_tb.vhd:180)
#             [22;96;49m0 ps[0m - [1;37;49mdefault[0m              -    [1;37;49mINFO[0m - -------------------------------------------------------------------------------- (svpwm_vunit_tb.vhd:181)
#         [22;96;49m30001 ps[0m - [1;37;49mcheck[0m                -    [1;32;49mPASS[0m - gate_u reset check (svpwm_vunit_tb.vhd:185)
#         [22;96;49m30001 ps[0m - [1;37;49mcheck[0m                -    [1;32;49mPASS[0m - gate_u_l reset check (svpwm_vunit_tb.vhd:186)
#         [22;96;49m30001 ps[0m - [1;37;49mcheck[0m                -    [1;32;49mPASS[0m - gate_v reset check (svpwm_vunit_tb.vhd:187)
#         [22;96;49m30001 ps[0m - [1;37;49mcheck[0m                -    [1;32;49mPASS[0m - gate_v_l reset check (svpwm_vunit_tb.vhd:188)
#         [22;96;49m30001 ps[0m - [1;37;49mcheck[0m                -    [1;32;49mPASS[0m - gate_w reset check (svpwm_vunit_tb.vhd:189)
#         [22;96;49m30001 ps[0m - [1;37;49mcheck[0m                -    [1;32;49mPASS[0m - gate_w_l reset check (svpwm_vunit_tb.vhd:190)
#         [22;96;49m30001 ps[0m - [1;37;49mdefault[0m              -    [1;37;49mINFO[0m - ==== TEST CASE FINISHED ===== (svpwm_vunit_tb.vhd:192)
# Break in Subprogram stop at C:/Python310/Lib/site-packages/vunit_hdl-4.6.1rc0-py3.10.egg/vunit/vhdl/core/src/stop_body_2008p.vhd line 13
# Stopped at C:/Python310/Lib/site-packages/vunit_hdl-4.6.1rc0-py3.10.egg/vunit/vhdl/core/src/stop_body_2008p.vhd line 13
